language: python
python:
  - "3.5"
  - "3.6"

env:
  - "MPI=mpich"
  - "MPI=openmpi"

os: linux
dist: trusty
sudo: required

git:
  depth: 3

cache:
  - pip
  - apt

branches:
  only:
    - master
    - develop
    - test

before_install:
  - ./conf/install-blas.sh
  - ./conf/install-mpi.sh $MPI
  - python -m pip install Cython
  - python --version
  - python -m cython --version
  - python -c "import numpy;print(numpy.__version__)"
  - if [[ "$MPI" == "mpich"   ]]; then mpichversion; fi
  - if [[ "$MPI" == "openmpi" ]]; then ompi_info;    fi

install:
  - python -m pip install --process-dependency-links .[mpi]

before_script:
  - if [[ "$MPI" == "mpich" ]]; then P=2; else P=5; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];  then P=2; fi

script:
  - ./conf/environment.sh
  # Test without MPI
  - python setup.py test
  # Test with MPI
  - mpiexec -n $P python run_mpi_test.py
